//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Feb 17 15:49:59 2015 by ROOT version 5.34/09)
//      from the StreamerInfo in file /storage/epp2/phskaj/pidSkims/prod6B/electronPair/fullSkim.electronPair.production006_B_mcp_neut_2010-02-water_magnet_run1.1of11.root
//////////////////////////////////////////////////////////


#ifndef ND__TTrackerECALPi0ReconModule_h
#define ND__TTrackerECALPi0ReconModule_h
namespace ND {
class TTrackerECALPi0ReconModule;
} // end of namespace.

#include "ND__TAnalysisReconModuleBase.h"

namespace ND {
class TTrackerECALPi0ReconModule : public ND::TAnalysisReconModuleBase {

public:
// Nested classes declaration.

public:
// Data Members.

   TTrackerECALPi0ReconModule();
   TTrackerECALPi0ReconModule(const TTrackerECALPi0ReconModule & );
   virtual ~TTrackerECALPi0ReconModule();

   ClassDef(TTrackerECALPi0ReconModule,3); // Generated by MakeProject.
};
} // namespace
#endif
