//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Feb 17 15:49:59 2015 by ROOT version 5.34/09)
//      from the StreamerInfo in file /storage/epp2/phskaj/pidSkims/prod6B/electronPair/fullSkim.electronPair.production006_B_mcp_neut_2010-02-water_magnet_run1.1of11.root
//////////////////////////////////////////////////////////


#ifndef ND__TAnalysisModuleBase_h
#define ND__TAnalysisModuleBase_h
namespace ND {
class TAnalysisModuleBase;
} // end of namespace.

#include "TNamed.h"
#include "TTree.h"
#include "Riostream.h"
#include <string>

namespace ND {
class TAnalysisModuleBase : public TNamed {

public:
// Nested classes declaration.

public:
// Data Members.
   Bool_t      fIsEnabled;    //
   Bool_t      fIsUsedForPreselection;    //
   TTree*      fOutputTree;               //
   Int_t       fBufferSize;               //Buffer Size for TBranch.
   Int_t       fSplitLevel;               ///< Split Level for TBranch.
   string      fDescription;              ///< A longish descrition of the analysis
   string      fCVSTagName;               ///< Defined if an official tagged version
   string      fCVSID;                    ///< Defined if an official tagged version
   Int_t       fRunID;                    //
   Int_t       fSubrunID;                 //
   Int_t       fEventID;                  //
   Int_t       fPreselected;              //
   string      fInputDirectory;           ///< An input directory where analysis modules can search for extra files.

   TAnalysisModuleBase();
   TAnalysisModuleBase(const TAnalysisModuleBase & );
   virtual ~TAnalysisModuleBase();

   ClassDef(TAnalysisModuleBase,3); // Generated by MakeProject.
};
} // namespace
#endif
