//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Feb 17 15:49:59 2015 by ROOT version 5.34/09)
//      from the StreamerInfo in file /storage/epp2/phskaj/pidSkims/prod6B/electronPair/fullSkim.electronPair.production006_B_mcp_neut_2010-02-water_magnet_run1.1of11.root
//////////////////////////////////////////////////////////


#ifndef ND__TNRooTrackerVtxModule_h
#define ND__TNRooTrackerVtxModule_h
namespace ND {
class TNRooTrackerVtxModule;
} // end of namespace.

#include "ND__TRooTrackerVtxModuleBase.h"

namespace ND {
class TNRooTrackerVtxModule : public ND::TRooTrackerVtxModuleBase {

public:
// Nested classes declaration.

public:
// Data Members.

   TNRooTrackerVtxModule();
   TNRooTrackerVtxModule(const TNRooTrackerVtxModule & );
   virtual ~TNRooTrackerVtxModule();

   ClassDef(TNRooTrackerVtxModule,3); // Generated by MakeProject.
};
} // namespace
#endif
