//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Feb 17 15:49:59 2015 by ROOT version 5.34/09)
//      from the StreamerInfo in file /storage/epp2/phskaj/pidSkims/prod6B/electronPair/fullSkim.electronPair.production006_B_mcp_neut_2010-02-water_magnet_run1.1of11.root
//////////////////////////////////////////////////////////


#ifndef ND__TGRooTrackerVtxModule_h
#define ND__TGRooTrackerVtxModule_h
namespace ND {
class TGRooTrackerVtxModule;
} // end of namespace.

#include "ND__TRooTrackerVtxModuleBase.h"

namespace ND {
class TGRooTrackerVtxModule : public ND::TRooTrackerVtxModuleBase {

public:
// Nested classes declaration.

public:
// Data Members.

   TGRooTrackerVtxModule();
   TGRooTrackerVtxModule(const TGRooTrackerVtxModule & );
   virtual ~TGRooTrackerVtxModule();

   ClassDef(TGRooTrackerVtxModule,3); // Generated by MakeProject.
};
} // namespace
#endif
