//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Feb 17 15:49:59 2015 by ROOT version 5.34/09)
//      from the StreamerInfo in file /storage/epp2/phskaj/pidSkims/prod6B/electronPair/fullSkim.electronPair.production006_B_mcp_neut_2010-02-water_magnet_run1.1of11.root
//////////////////////////////////////////////////////////


#ifndef ND__TECALTestbeamModule_h
#define ND__TECALTestbeamModule_h
namespace ND {
class TECALTestbeamModule;
} // end of namespace.

#include "ND__TAnalysisReconModuleBase.h"

namespace ND {
class TECALTestbeamModule : public ND::TAnalysisReconModuleBase {

public:
// Nested classes declaration.

public:
// Data Members.
   int         Cerenkov1Lo[23];    //
   int         Cerenkov2Lo[23];    //
   int         Cerenkov1Hi[23];    //
   int         Cerenkov2Hi[23];    //
   int         TOF[23];            //
   int         TriggerWord;        //
   int         PIDResult;          //
   double      Momentum;           //
   int         Angle;              //

   TECALTestbeamModule();
   TECALTestbeamModule(const TECALTestbeamModule & );
   virtual ~TECALTestbeamModule();

   ClassDef(TECALTestbeamModule,3); // Generated by MakeProject.
};
} // namespace
#endif
